<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>DyingLightXuiEditor</AssemblyName>
    <RootNamespace>XuiEditor.Wpf</RootNamespace>
    <ApplicationIcon>Assets\DyingLightXuiEditor.ico</ApplicationIcon>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <PackageId>Dying Light XUI Editor</PackageId>
    <Title>Dying Light XUI Editor</Title>
    <Authors>BalancedLight</Authors>
    <Product>$(Title)</Product>
    <Description>An easy to use GUI to edit Dying Light's XUI files</Description>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugSymbols>false</DebugSymbols>
    <DebugType>None</DebugType>
    <StandalonePublishDirectory>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\..\..\artifacts\publish\win-x64\'))</StandalonePublishDirectory>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\XuiEditor.Core\XuiEditor.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\MovingGears.gif" />
    <EmbeddedResource Include="Localization\Strings.En.json"
                      WithCulture="false" />
  </ItemGroup>
  <Target Name="PublishStandaloneExecutableAfterReleaseBuild" AfterTargets="Build" Condition="'$(Configuration)' == 'Release' and '$(DesignTimeBuild)' != 'true' and '$(_IsPublishing)' != 'true'">
    <MSBuild Projects="$(MSBuildProjectFullPath)" Targets="Publish" BuildInParallel="false" Properties="Configuration=$(Configuration);RuntimeIdentifier=win-x64;SelfContained=true;PublishSingleFile=true;PublishDir=$(StandalonePublishDirectory);_IsPublishing=true" />
    <Message Importance="High" Text="Standalone executable -&gt; $(StandalonePublishDirectory)DyingLightXuiEditor.exe" />
  </Target>
</Project>
