<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableMSTestRunner>true</EnableMSTestRunner>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="..\..\src\XuiEditor.Core\XuiEditor.Core.csproj" />
    <ProjectReference Include="..\..\src\XuiEditor.Wpf\XuiEditor.Wpf.csproj" />
  </ItemGroup>
</Project>
